apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use prometheus operator as base
resources:
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.59/bundle.yaml

# Change the node selector
patches:
- path: prom_operator_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: prometheus-operator
    version: v1
