# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'valkey-client'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['valkey-client-isolated:3003']  
  - job_name: 'datagen'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['datagen:9605']  
  - job_name: 'datafwd'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['datafwd:9606']  